# Generated by Django 5.0.7 on 2025-12-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_coverage_radius_miles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
