# Generated by Django 5.0.7 on 2025-12-03 01:15

from django.db import migrations, models

import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_contact_email_profile_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.models.banner_upload_path,
            ),
        ),
    ]
