# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models


def hero_upload_path(instance, filename):
    return f"heroes/user_{instance.user_id}/{filename}"


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_contact_email_profile_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to=hero_upload_path),
        ),
        migrations.AddField(
            model_name="profile",
            name="hero_image_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
