# Generated by ChatGPT on 2025-02-14

from django.db import migrations, models
import accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_contact_email_profile_contact_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.hero_upload_path),
        ),
    ]
