# Generated by Django 5.0.7 on 2025-12-16 20:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_contact_email_profile_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coverage_radius_miles',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_location',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.banner_upload_path),
        ),
    ]
