# Generated by Django 5.0.7 on 2026-03-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profilelike_profilelike_unique_profile_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allow_direct_messages',
            field=models.BooleanField(default=False),
        ),
    ]
