# Generated by Django 5.0.7 on 2026-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_allow_direct_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hero_blurb',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_headline',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
