# Generated by Django 5.0.7 on 2026-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_hero_blurb_profile_hero_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_contact_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_contact_phone',
            field=models.BooleanField(default=False),
        ),
    ]
