# Generated by Django 5.0.7 on 2026-03-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_show_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
