# Generated by Django 5.0.7 on 2026-03-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dm_opt_out_reason',
            field=models.CharField(blank=True, choices=[('too_many', 'Too many messages'), ('spam', 'Spam'), ('not_ready', 'Not ready yet'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dm_opt_out_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='allow_direct_messages',
            field=models.BooleanField(default=True),
        ),
    ]
