# Generated by Django 5.0.7 on 2026-04-07 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_dm_opt_out_reason_profile_dm_opt_out_until_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('saved_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_saves_received', to=settings.AUTH_USER_MODEL)),
                ('saver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_saves_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='profilesave',
            constraint=models.UniqueConstraint(fields=('saver', 'saved_user'), name='unique_profile_save'),
        ),
    ]
