# Generated by Codex on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_profilesave_profilesave_unique_profile_save"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("contractor", "Contractor"),
                    ("homeowner", "Homeowner"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
