# Generated by Django 5.0.7 on 2026-04-16 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='frozen_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
