# Generated by Django 5.0.7 on 2026-04-17 12:27

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_frozen_at_profile_frozen_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='public_profile_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HomeownerReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.homeowner_reference_upload_path)),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeowner_reference_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at', '-id'],
            },
        ),
    ]
