# Generated by Django 5.0.7 on 2026-04-24 22:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_backfill_homeowner_direct_messages'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('admin_login', 'Admin login'), ('admin_access_denied', 'Admin access denied'), ('staff_access_updated', 'Staff access updated'), ('report_updated', 'Report updated'), ('moderation_action', 'Moderation action'), ('profile_updated', 'Profile updated'), ('user_updated', 'User updated')], max_length=40)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_events_about_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('support', 'Support'), ('moderator', 'Moderator'), ('compliance', 'Compliance'), ('superadmin', 'Superadmin')], default='support', max_length=20)),
                ('can_access_admin', models.BooleanField(default=False)),
                ('can_manage_accounts', models.BooleanField(default=False)),
                ('can_manage_moderation', models.BooleanField(default=False)),
                ('can_manage_verification', models.BooleanField(default=False)),
                ('can_manage_compliance', models.BooleanField(default=False)),
                ('require_password_reset', models.BooleanField(default=False)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_access_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff access',
                'verbose_name_plural': 'Staff access',
                'ordering': ['user__username', 'user__email', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('safety', 'Safety'), ('fraud', 'Fraud'), ('impersonation', 'Impersonation'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('copyright', 'Copyright'), ('child_safety', 'Child safety'), ('illegal_content', 'Illegal content'), ('other', 'Other')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_review', 'In review'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('details', models.TextField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_user_reports', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_items', to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('warn_user', 'Warn user'), ('freeze_profile', 'Freeze profile'), ('unfreeze_profile', 'Unfreeze profile'), ('deactivate_account', 'Deactivate account'), ('reactivate_account', 'Reactivate account'), ('hide_content', 'Hide content'), ('restore_content', 'Restore content'), ('remove_content', 'Remove content'), ('disable_direct_messages', 'Disable direct messages'), ('enable_direct_messages', 'Enable direct messages'), ('mark_verified', 'Mark verified'), ('reject_verification', 'Reject verification'), ('copyright_takedown', 'Copyright takedown')], max_length=40)),
                ('public_note', models.TextField(blank=True, default='')),
                ('internal_note', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='accounts.userreport')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
