# Generated by Django 5.0.7 on 2026-04-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_insurance_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('verified', 'Reviewed'), ('rejected', 'Rejected'), ('expired', 'Review expired')], default='unverified', max_length=20),
        ),
    ]
