# Generated by Django 5.0.7 on 2026-05-06 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_businessdirectorylisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdirectorylisting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
