# Generated by Django 5.0.7 on 2026-05-07 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_businessdirectorylisting_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDirectoryListingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_directory_likes_given', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.businessdirectorylisting')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='businessdirectorylistinglike',
            constraint=models.UniqueConstraint(fields=('liker', 'listing'), name='unique_business_directory_listing_like'),
        ),
    ]
