# Generated by Django 5.0.7 on 2026-05-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_businessdirectorylistinglike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdirectorylisting',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdirectorylisting',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessdirectorylisting',
            name='service_radius_miles',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
