# Generated by Django 5.0.7 on 2026-05-21 18:07

from django.db import migrations, models


US_STATES = {
    "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID",
    "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS",
    "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK",
    "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV",
    "WI", "WY", "DC",
}
CANADIAN_PROVINCES = {
    "AB", "BC", "MB", "NB", "NL", "NS", "NT", "NU", "ON", "PE", "QC", "SK", "YT",
    "ALBERTA", "BRITISH COLUMBIA", "MANITOBA", "NEW BRUNSWICK", "NEWFOUNDLAND",
    "NEWFOUNDLAND AND LABRADOR", "NOVA SCOTIA", "NORTHWEST TERRITORIES", "NUNAVUT",
    "ONTARIO", "PRINCE EDWARD ISLAND", "QUEBEC", "SASKATCHEWAN", "YUKON",
}


def infer_country_code(location):
    tokens = [token.strip().upper().rstrip(".") for token in str(location or "").split(",") if token.strip()]
    for token in reversed(tokens):
        if token in {"CANADA", "CA"} or token in CANADIAN_PROVINCES:
            return "CA"
        if token in {"USA", "US", "UNITED STATES"} or token in US_STATES:
            return "US"
    return ""


def backfill_country_codes(apps, schema_editor):
    BusinessDirectoryListing = apps.get_model("accounts", "BusinessDirectoryListing")
    for listing in BusinessDirectoryListing.objects.filter(country_code="").only("id", "location", "country_code"):
        country_code = infer_country_code(listing.location)
        if country_code:
            listing.country_code = country_code
            listing.save(update_fields=["country_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_businessdirectorylisting_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdirectorylisting',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
        migrations.RunPython(backfill_country_codes, migrations.RunPython.noop),
    ]
