# Generated by Django 5.0.7 on 2026-05-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_businessdirectorylisting_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contractor_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='contractor_primary_category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
