# Generated by Django 5.0.7 on 2025-12-02 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_messagethread_privatemessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagethread',
            name='unique_project_client_thread',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='client_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='client_blocked_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='client_has_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='owner_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='owner_blocked_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='owner_has_accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messagethread',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_threads', to='portfolio.project'),
        ),
        migrations.AddConstraint(
            model_name='messagethread',
            constraint=models.UniqueConstraint(fields=('owner', 'client'), name='unique_dm_pair'),
        ),
    ]
