# Generated by Django 5.0.7 on 2025-12-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_projectfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='material_label',
            field=models.CharField(blank=True, help_text="Short title/description for the material/tool (e.g. 'DeWalt Drill – $129').", max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='material_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
