# Generated by Django 5.0.7 on 2025-12-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_material_label_project_material_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='extra_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/covers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='material_label',
            field=models.CharField(blank=True, help_text="Short title/description for the material/tool (e.g. 'DeWalt Drill – $129').", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
