# Generated by Django 5.0.7 on 2025-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_extra_links_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_job_posting',
            field=models.BooleanField(default=False),
        ),
    ]
