# Generated by Django 5.0.7 on 2025-12-16 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_extra_links_alter_project_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profiles/logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='profiles/banners/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', related_query_name='portfolio_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
