# Generated by Django 5.0.7 on 2026-03-06 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_is_job_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='cover_image',
            new_name='cover_image_file',
        ),
        migrations.AddField(
            model_name='project',
            name='compliance_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='cover_image_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_projects', to='portfolio.projectimage'),
        ),
        migrations.AddField(
            model_name='project',
            name='job_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='larger_project_details',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='notify_by_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='part_of_larger_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='permit_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='permit_responsible_party',
            field=models.CharField(blank=True, choices=[('contractor', 'Contractor handles filing'), ('homeowner', 'Homeowner handles filing')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='post_privacy',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='private_contractor_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='required_expertise',
            field=models.CharField(blank=True, choices=[('licensed_pro', 'Licensed Professional'), ('handyman', 'Handyman / Expert Help')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='service_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
