# Generated by Django 5.0.7 on 2025-12-16 21:01

from django.db import migrations


def copy_portfolio_profiles(apps, schema_editor):
    PortfolioProfile = apps.get_model("portfolio", "Profile")
    AccountsProfile = apps.get_model("accounts", "Profile")

    for old_profile in PortfolioProfile.objects.all():
        profile, _ = AccountsProfile.objects.get_or_create(user_id=old_profile.user_id)

        if old_profile.logo and not profile.logo:
            profile.logo = old_profile.logo
        if old_profile.banner and not profile.banner:
            profile.banner = old_profile.banner

        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_profile"),
        ("accounts", "0006_profile_bio_profile_company_name_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_portfolio_profiles, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
