# Generated by Django 5.0.7 on 2026-03-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_cover_image_project_cover_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='job_is_published',
            field=models.BooleanField(default=False),
        ),
    ]
