# Generated by Django 5.0.7 on 2026-03-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_job_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='client_ignored_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='owner_ignored_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
