# Generated by Django 5.0.7 on 2026-03-25 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_messagethread_client_ignored_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='testimonial_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
