# Generated by Django 5.0.7 on 2026-03-25 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_is_testimonial_project_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_testimonial',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='project',
            name='testimonial_published',
        ),
        migrations.RemoveField(
            model_name='project',
            name='testimonial_published_at',
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='is_testimonial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='testimonial_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='testimonial_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
