# Generated by Django 5.0.7 on 2026-03-28 23:18

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_project_is_testimonial_remove_project_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='portfolio.privatemessage'),
        ),
        migrations.AlterField(
            model_name='privatemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=portfolio.models.direct_message_upload_path),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('camera', 'Camera'), ('link', 'Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to=portfolio.models.message_attachment_upload_path)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portfolio.privatemessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
