# Generated by Django 5.0.7 on 2026-03-29 23:13

import django.db.models.deletion
import portfolio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_privatemessage_parent_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('revised', 'Revised'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bids', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='portfolio.project')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBidVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('price_type', models.CharField(choices=[('fixed', 'Fixed price'), ('range', 'Estimate range')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('timeline_text', models.CharField(blank=True, default='', max_length=255)),
                ('proposal_text', models.TextField(blank=True, default='')),
                ('included_text', models.TextField(blank=True, default='')),
                ('excluded_text', models.TextField(blank=True, default='')),
                ('payment_terms', models.TextField(blank=True, default='')),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=portfolio.models.project_bid_attachment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='portfolio.projectbid')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bid_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectbid',
            name='accepted_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_bids', to='portfolio.projectbidversion'),
        ),
        migrations.AddConstraint(
            model_name='projectbidversion',
            constraint=models.UniqueConstraint(fields=('bid', 'version_number'), name='unique_bid_version_number'),
        ),
        migrations.AddConstraint(
            model_name='projectbid',
            constraint=models.UniqueConstraint(fields=('project', 'contractor'), name='unique_project_bid_per_contractor'),
        ),
    ]
