# Generated by Django 5.0.7 on 2026-06-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_projectimage_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectplan',
            name='markup_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
