# Generated by Django 5.0.7 on 2026-07-04 12:12

import django.db.models.deletion
import portfolio.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_projectplan_guided_intake_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general_feedback', 'General Feedback'), ('technical_support', 'Technical Support'), ('copyright_content_report', 'Copyright & Content Report'), ('customer_service', 'Customer Service')], max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('links', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('new', 'New'), ('work_in_progress', 'Work in progress'), ('needs_more_supporting_documents', 'Needs more supporting documents'), ('resolved', 'Resolved'), ('removed', 'Removed')], default='new', max_length=40)),
                ('internal_admin_note', models.TextField(blank=True)),
                ('resolved_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=portfolio.models.feedback_attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portfolio.feedbackticket')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
