# Generated by Django 5.0.7 on 2026-07-06 14:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_feedbackreply_feedbackattachment_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('service_radius_miles', models.PositiveIntegerField(default=15)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('either', 'Either')], default='email', max_length=10)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('other_skill', models.CharField(blank=True, default='', max_length=100)),
                ('availability', models.JSONField(blank=True, default=list)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('1_3_years', '1-3 years'), ('3_10_years', '3-10 years'), ('10_plus_years', '10+ years')], max_length=20)),
                ('bio', models.CharField(blank=True, default='', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('admin_approved', models.BooleanField(default=False)),
                ('contact_verified', models.BooleanField(default=False)),
                ('contact_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HelperFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(max_length=120)),
                ('worked_together', models.BooleanField(default=False)),
                ('reliability_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_quality_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('would_hire_again', models.BooleanField(default=False)),
                ('short_note', models.CharField(blank=True, default='', max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_feedback', to=settings.AUTH_USER_MODEL)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='portfolio.helperlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
