# Generated by Django 5.0.7 on 2026-07-05 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_feedbackreply_feedbackattachment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website_url', models.URLField(max_length=1000)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('service_radius_miles', models.PositiveIntegerField(default=25)),
                ('refresh_interval_hours', models.PositiveIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('paused_due_to_failures', models.BooleanField(default=False)),
                ('consecutive_failures', models.PositiveIntegerField(default=0)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('last_successful_scrape_at', models.DateTimeField(blank=True, null=True)),
                ('last_promotions_found', models.PositiveIntegerField(default=0)),
                ('last_promotions_added', models.PositiveIntegerField(default=0)),
                ('last_promotions_updated', models.PositiveIntegerField(default=0)),
                ('last_promotions_expired', models.PositiveIntegerField(default=0)),
                ('scrape_status', models.CharField(choices=[('not_scraped', 'Not scraped'), ('success', 'Success'), ('failed', 'Failed'), ('no_promotions_found', 'No promotions found')], default='not_scraped', max_length=40)),
                ('scrape_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['business_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_scraped', 'Not scraped'), ('success', 'Success'), ('failed', 'Failed'), ('no_promotions_found', 'No promotions found')], max_length=40)),
                ('promotions_found', models.PositiveIntegerField(default=0)),
                ('promotions_added', models.PositiveIntegerField(default=0)),
                ('promotions_updated', models.PositiveIntegerField(default=0)),
                ('promotions_expired', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='portfolio.promotionsource')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('promotion_text', models.TextField()),
                ('product_or_service_name', models.CharField(blank=True, default='', max_length=255)),
                ('original_price', models.CharField(blank=True, default='', max_length=80)),
                ('sale_price', models.CharField(blank=True, default='', max_length=80)),
                ('discount_text', models.CharField(blank=True, default='', max_length=160)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=80)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('website_url', models.URLField(max_length=1000)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('zip_code', models.CharField(blank=True, default='', max_length=20)),
                ('applies_to_homeowners', models.BooleanField(default=True)),
                ('applies_to_contractors', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('admin_approved', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_excerpt', models.TextField(blank=True, default='')),
                ('content_fingerprint', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('missing_since', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='portfolio.promotionsource')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['admin_approved', 'is_active'], name='portfolio_l_admin_a_18149e_idx'), models.Index(fields=['category', 'city'], name='portfolio_l_categor_8f06c3_idx')],
            },
        ),
    ]
