# Generated by Django 5.0.7 on 2026-07-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_promotionsource_promotionscrapelog_localpromotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpromotion',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
    ]
