# Generated by Django 5.0.7 on 2026-07-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_localpromotion_source_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionsource',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
