# Generated by Django 5.0.7 on 2026-07-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_alter_promotionsource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionsource',
            name='refresh_interval_hours',
            field=models.PositiveIntegerField(blank=True, default=24),
        ),
        migrations.AlterField(
            model_name='promotionsource',
            name='service_radius_miles',
            field=models.PositiveIntegerField(blank=True, default=25),
        ),
    ]
