# Generated by Django 5.0.7 on 2026-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_projectestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='calculation_version',
            field=models.CharField(default='painting-v2', max_length=40),
        ),
    ]
