# Generated by Django 5.0.7 on 2026-09-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_projectestimate_calculation_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='calculation_version',
            field=models.CharField(default='painting-v3', max_length=40),
        ),
    ]
