# Generated by Django 5.0.7 on 2026-09-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_projectestimate_calculation_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectestimate',
            name='calculation_version',
            field=models.CharField(default='painting-v4', max_length=40),
        ),
    ]
