# Generated by Django 5.0.7 on 2026-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_projectestimate_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing')], default='painting', max_length=40),
        ),
    ]
