# Generated by Django 5.0.7 on 2026-09-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_alter_projectestimate_estimate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing'), ('drywall', 'Drywall')], default='painting', max_length=40),
        ),
    ]
