# Generated by Django 5.0.7 on 2026-09-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_add_paving_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing'), ('drywall', 'Drywall'), ('paving', 'Paving'), ('roofing', 'Roofing')], default='painting', max_length=40),
        ),
    ]
