# Generated by Django 5.0.7 on 2026-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_add_decking_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing'), ('drywall', 'Drywall'), ('paving', 'Paving'), ('roofing', 'Roofing'), ('flooring', 'Flooring'), ('siding', 'Siding'), ('decking', 'Decking'), ('fencing', 'Fencing'), ('windows', 'Windows'), ('doors', 'Doors')], default='painting', max_length=40),
        ),
    ]
