# Generated by Django 5.0.7 on 2026-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0045_add_fencing_windows_doors_estimates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing'), ('drywall', 'Drywall'), ('paving', 'Paving'), ('roofing', 'Roofing'), ('flooring', 'Flooring'), ('siding', 'Siding'), ('decking', 'Decking'), ('fencing', 'Fencing'), ('windows', 'Windows'), ('doors', 'Doors'), ('garage_coating', 'Garage floor coating')], default='painting', max_length=40),
        ),
    ]
