# Generated by Django 5.0.7 on 2026-09-25

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_add_garage_coating_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimate',
            name='contractor_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='homeowner_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='shared_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_project_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='workflow_status',
            field=models.CharField(choices=[('owner_draft', 'Homeowner draft'), ('shared', 'Shared with contractor'), ('contractor_revised', 'Contractor revision returned')], default='owner_draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectestimate',
            name='estimate_type',
            field=models.CharField(choices=[('painting', 'Painting'), ('framing', 'Framing'), ('drywall', 'Drywall'), ('paving', 'Paving'), ('roofing', 'Roofing'), ('flooring', 'Flooring'), ('siding', 'Siding'), ('decking', 'Decking'), ('fencing', 'Fencing'), ('windows', 'Windows'), ('doors', 'Doors'), ('garage_coating', 'Garage floor coating'), ('electrical', 'Electrical')], default='painting', max_length=40),
        ),
    ]
