# Generated by Django 5.0.7 on 2026-09-26 02:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0048_alter_projectestimate_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectestimate',
            name='client_share_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='client_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='projectestimate',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_estimates', to=settings.AUTH_USER_MODEL),
        ),
    ]
