# Generated by Django 5.0.7 on 2026-10-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_projectestimate_client_share_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroVideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(unique=True)),
                ('viewer_id', models.UUIDField(db_index=True)),
                ('source', models.CharField(default='homepage', max_length=16)),
                ('watch_seconds', models.FloatField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('replays', models.PositiveIntegerField(default=0)),
                ('share_actions', models.PositiveIntegerField(default=0)),
                ('copy_actions', models.PositiveIntegerField(default=0)),
                ('email_actions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intro video analytics',
                'verbose_name_plural': 'Intro video analytics',
            },
        ),
    ]
